### ISSUE TITLE
Missing library "jinja2" for json_exporter

### ISSUE THREAD

**Issue by adaichendt-tv1** [bodsch/ansible-collection-prometheus#1]
Hey,

upon installation of the json_exporter, an error occurs: 

```
TASK [bodsch.prometheus.json_exporter : create custom fact file] *****************************************************************************************************************************
fatal: [redacted]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDOUT:


Traceback (most recent call last):
  File "/home/lxadmin/.ansible/tmp/ansible-tmp-1693414609.1921391-366756-73945771632527/AnsiballZ_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/lxadmin/.ansible/tmp/ansible-tmp-1693414609.1921391-366756-73945771632527/AnsiballZ_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/lxadmin/.ansible/tmp/ansible-tmp-1693414609.1921391-366756-73945771632527/AnsiballZ_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.bodsch.core.plugins.modules.facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bodsch.core.facts_payload_7i0jd4k1/ansible_bodsch.core.facts_payload.zip/ansible_collections/bodsch/core/plugins/modules/facts.py", line 15, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/ansible_bodsch.core.facts_payload_7i0jd4k1/ansible_bodsch.core.facts_payload.zip/ansible_collections/bodsch/core/plugins/module_utils/template/template.py", line 8, in <module>
ModuleNotFoundError: No module named 'jinja2'



MODULE_STDERR:

Shared connection to redacted closed.
```

after installing the package manually, the role terminated without error.

thanks for this role :)

**Comment by bodsch** [comment]
Thank you for your issue. I will take care of it.

**Comment by bodsch** [comment]
I have solved the error in the dependent collection (bodsch.core).
